name: suckit
base: core18
adopt-info: suckit
summary: suckit
description: |
  SuckIT allows you to recursively visit and download a website's content to your disk.

grade: stable
confinement: strict

parts:
  suckit:
    plugin: rust
    source: https://github.com/Skallwar/suckit.git
    build-packages:
      - pkg-config
      - libssl-dev
    override-pull: |
      set -eu
      snapcraftctl pull
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "latest/beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        cd ../src
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version $(git -C ../src describe --tags  | sed 's/v//')

apps:
  suckit:
    command: suckit
    plugs:
      - network
      - home
      - removable-media
